# Generated by Django 5.2.4 on 2025-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='recipient',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
