# Generated by Django 5.2.4 on 2025-08-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0002_emaillog_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='sent_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='status',
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
    ]
