# Generated by Django 5.2.4 on 2025-08-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0003_rename_sent_at_emaillog_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_core.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_core.contact')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'original_name'], name='crm_core_fi_created_96231c_idx')],
            },
        ),
    ]
