# Generated by Django 5.2.5 on 2025-08-21 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0006_contact_company_contact_created_at_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=64)),
                ('direction', models.CharField(choices=[('in', 'Eingehend'), ('out', 'Ausgehend'), ('missed', 'Verpasst')], max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Gestartet'), ('ringing', 'Klingelt'), ('answered', 'Angenommen'), ('failed', 'Fehlgeschlagen'), ('completed', 'Beendet')], default='initiated', max_length=12)),
                ('source', models.CharField(choices=[('sipgate', 'Sipgate'), ('fritzbox', 'Fritz!Box'), ('manual', 'Manuell')], default='sipgate', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='crm_core.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='crm_core.contact')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
