# Generated by Django 5.2.5 on 2025-09-13 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0008_expensedraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='mail', max_length=20)),
                ('source_message_id', models.CharField(blank=True, max_length=255)),
                ('source_attachment_id', models.CharField(blank=True, max_length=255)),
                ('attachment_sha256', models.CharField(blank=True, max_length=64)),
                ('pdf', models.FileField(blank=True, upload_to='invoices/source/%Y/%m/')),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=128)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['source_message_id', 'source_attachment_id'], name='crm_core_in_source__d371c7_idx'), models.Index(fields=['attachment_sha256'], name='crm_core_in_attachm_4a8c15_idx')],
            },
        ),
    ]
