# Generated by Django 5.2.5 on 2025-08-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='is_remote',
            field=models.BooleanField(default=True),
        ),
    ]
