# Generated by Django 5.2.5 on 2025-09-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0002_timeentry_is_remote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-start_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timeclock.project'),
        ),
    ]
